# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.5
  - 3.6

env:
  - DJANGO=1.11
  - DJANGO=2.0

install:
  - cd example
  - pip install -q Django==$DJANGO
  - pip install -r requirements/base.txt

script:
   coverage run --omit */site-packages/*,*/migrations/*,*/lib/* manage.py test issue_tracker.tests --settings=dj.settings -v 2

after_success:
  - codecov -e DJANGO
